import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { performance } from "node:perf_hooks";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const reportPath = path.join(root, "docs", "performance-report.md");

const commandTargets = [
  { id: "backend-build", label: "Backend build", command: "npm run build -w backend", warnMs: 45_000 },
  { id: "admin-build", label: "Admin build", command: "npm run build -w admin-dashboard", warnMs: 45_000 },
  { id: "desktop-build", label: "Desktop build", command: "npm run build -w desktop-app", warnMs: 90_000 },
  { id: "backend-test", label: "Backend tests", command: "npm run test -w backend", warnMs: 60_000 },
  { id: "desktop-test", label: "Desktop tests", command: "npm run test -w desktop-app", warnMs: 60_000 },
  { id: "admin-test", label: "Admin smoke tests", command: "npm run test -w admin-dashboard", warnMs: 30_000 }
];

const artifactTargets = [
  { label: "Admin built assets", directory: path.join(root, "admin-dashboard", "dist"), warnBytes: 5 * 1024 * 1024 },
  { label: "Desktop renderer assets", directory: path.join(root, "desktop-app", "dist-renderer"), warnBytes: 8 * 1024 * 1024 }
];

const startedAt = new Date();
const metadata = {
  timestamp: startedAt.toISOString(),
  branch: gitValue(["branch", "--show-current"]) || "unknown",
  commit: gitValue(["rev-parse", "--short", "HEAD"]) || "unknown",
  node: process.version,
  npm: commandValue("npm --version") || "unknown",
  os: `${os.type()} ${os.release()} ${os.arch()}`,
  cpu: `${os.cpus()[0]?.model ?? "Unknown CPU"} (${os.cpus().length} logical cores)`,
  memory: `${formatBytes(os.totalmem())} total`
};

const commandResults = commandTargets.map(runProfileCommand);
const artifactResults = artifactTargets.map(measureArtifact);
const report = renderReport(metadata, commandResults, artifactResults);
writeFileSync(reportPath, report);

console.log(`Performance report written to ${path.relative(root, reportPath)}`);

const failedCommands = commandResults.filter((result) => result.exitCode !== 0);
if (failedCommands.length) {
  console.error(`Performance profiling failed: ${failedCommands.map((result) => result.label).join(", ")}`);
  process.exit(1);
}

function runProfileCommand(target) {
  console.log(`==> ${target.label}`);
  const started = performance.now();
  const result = spawnSync(target.command, {
    cwd: root,
    encoding: "utf8",
    shell: true,
    maxBuffer: 10 * 1024 * 1024
  });
  const durationMs = Math.round(performance.now() - started);
  return {
    ...target,
    durationMs,
    exitCode: result.status ?? 1,
    status: result.status === 0 ? (durationMs > target.warnMs ? "warn" : "pass") : "fail",
    stdout: summarizeOutput(result.stdout),
    stderr: summarizeOutput(result.stderr),
    error: result.error?.message
  };
}

function measureArtifact(target) {
  const sizeBytes = existsSync(target.directory) ? directorySize(target.directory) : 0;
  return {
    ...target,
    exists: existsSync(target.directory),
    sizeBytes,
    status: sizeBytes > target.warnBytes ? "warn" : "pass"
  };
}

function renderReport(meta, commands, artifacts) {
  const lines = [
    "# Performance Report",
    "",
    "Generated by `npm run profile:performance`.",
    "",
    "## Environment",
    "",
    `- Timestamp: ${meta.timestamp}`,
    `- Git: ${meta.branch} @ ${meta.commit}`,
    `- Node: ${meta.node}`,
    `- npm: ${meta.npm}`,
    `- OS: ${meta.os}`,
    `- CPU: ${meta.cpu}`,
    `- Memory: ${meta.memory}`,
    "",
    "## Command Timings",
    "",
    "| Target | Status | Duration | Warning Target | Exit |",
    "| --- | --- | ---: | ---: | ---: |",
    ...commands.map((result) => `| ${result.label} | ${statusLabel(result.status)} | ${formatMs(result.durationMs)} | ${formatMs(result.warnMs)} | ${result.exitCode} |`),
    "",
    "## Build Output Sizes",
    "",
    "| Target | Status | Size | Warning Target | Path |",
    "| --- | --- | ---: | ---: | --- |",
    ...artifacts.map((result) => `| ${result.label} | ${statusLabel(result.status)} | ${result.exists ? formatBytes(result.sizeBytes) : "missing"} | ${formatBytes(result.warnBytes)} | \`${path.relative(root, result.directory).replaceAll("\\", "/")}\` |`),
    "",
    "## Command Output Summaries",
    "",
    ...commands.flatMap((result) => commandSummary(result)),
    "## Notes",
    "",
    "- `warn` means a target exceeded its documented warning threshold, but the profiler still exits successfully.",
    "- `fail` means the profiled command returned a nonzero exit code; the report is still written before the script exits nonzero.",
    ""
  ];
  return lines.join("\n");
}

function commandSummary(result) {
  const lines = [
    `### ${result.label}`,
    "",
    `- Command: \`${result.command}\``,
    `- Duration: ${result.durationMs} ms (${formatMs(result.durationMs)})`,
    `- Status: ${statusLabel(result.status)}`,
    ""
  ];

  if (result.error) lines.push(`Error: ${result.error}`, "");
  if (result.stdout) lines.push("Stdout tail:", "", "```text", result.stdout, "```", "");
  if (result.stderr) lines.push("Stderr tail:", "", "```text", result.stderr, "```", "");
  if (!result.stdout && !result.stderr && !result.error) lines.push("No command output captured.", "");
  return lines;
}

function summarizeOutput(value) {
  const clean = (value ?? "")
    .replace(/\u001b\[[0-9;?]*[ -/]*[@-~]/g, "")
    .replace(/\r(?!\n)/g, "\n");
  const lines = clean.trim().split(/\r?\n/).filter(Boolean);
  return lines.slice(-25).join("\n");
}

function directorySize(directory) {
  let total = 0;
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) total += directorySize(entryPath);
    if (entry.isFile()) total += statSync(entryPath).size;
  }
  return total;
}

function gitValue(args) {
  const result = spawnSync("git", args, { cwd: root, encoding: "utf8" });
  return result.status === 0 ? result.stdout.trim() : "";
}

function commandValue(command) {
  const result = spawnSync(command, { cwd: root, encoding: "utf8", shell: true });
  return result.status === 0 ? result.stdout.trim() : "";
}

function formatMs(ms) {
  return `${(ms / 1000).toFixed(2)}s`;
}

function formatBytes(bytes) {
  if (!bytes) return "0 B";
  const units = ["B", "KB", "MB", "GB"];
  const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  return `${(bytes / 1024 ** index).toFixed(index === 0 ? 0 : 2)} ${units[index]}`;
}

function statusLabel(status) {
  if (status === "pass") return "pass";
  if (status === "warn") return "warn";
  return "fail";
}
